site_name: My Docs
site_url: http://doc.cblog.ch
repo_url: https://github.com/Excape/hsr-docs
site_description: HSR Study Documentation
site_author: Robin Suter

markdown-extensions:
  - toc
  - sane_lists
  
site_dir: /var/www/hsr-docs
